set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-kitty:RGB"

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Reload config keybind
bind r source-file ~/.tmux.conf \; display-message "Tmux config reloaded!"

# Status bar at the top
set -g status-position top

# Index panes and windows from 1
set -g base-index 1
setw -g pane-base-index 1

# Status bar style
set -g status-style "bg=default,fg=default"

# Left side: Prefix indicator + Session name
set -g status-left-length 40
set -g status-left "#[fg=black,bg=blue,bold]#{?client_prefix,  ,  }#[fg=blue,bg=default]#[fg=blue,bg=default]#[fg=black,bg=blue,bold] #S #[fg=blue,bg=default]"

# Righ side: RAM
set -g status-right '#[fg=blue,bg=default]#[fg=black,bg=blue]   #[fg=blue,bg=default]#[fg=blue,bg=default]#[fg=black,bg=blue,bold] #(free -h | awk "/^Mem:/ {print \$3 }") '


# Move the windows tabs to center
set -g status-justify centre

# Status bar window formats
setw -g window-status-format '#[fg=white,bg=default,bold] #I:#W '
setw -g window-status-current-format '#[fg=black,bg=blue,bold] #I:#W '



