# Tokyo Night
include tokyo-night-theme.conf

# Font
font_family CaskaydiaCove Nerd Font
font_size 13
disable_ligatures never

# Cursor
shell_integration no-cursor
cursor_shape block
cursor_blink true
cursor_trail 10
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

# Window
window_padding_width 1
hide_window_decorations yes

# Remote Control
allow_remote_control yes

# Behavior
shell zsh
enable_audio_bell no
confirm_os_window_close 0
copy_on_select clipboard

# Remap / Keybinding
mouse_map right click grabbed
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map shift+enter send_text all \x1b\r
